server:
  port: 8086
spring:
  application:
    name: image
  data:
    mongodb:
      uri: mongodb://localhost:27017/images
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka