server:
  port: 8086
spring:
  application:
    name: image
  data:
    mongodb:
      uri: mongodb+srv://bmn:cntt2project@cluster0.xge7gs5.mongodb.net/?retryWrites=true&w=majority
      database: images
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka