version: "3.7"

services:
  frontend:
    build:
      context: ../Ecommerce.Website/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always

  backend:
    build: 
      context: ../Ecommerce.Api/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always