services:
  ecom-potgres:
    container_name: ecom-potgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: images
    ports:
      - "27017:27017"